// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-QomAnNC8Q5N0KNIO4mRsdX2L1fD5Do',
    appId: '1:9580367963:web:4cfef350f58b50a930af7e',
    messagingSenderId: '9580367963',
    projectId: 'cinemax-app-8ea71',
    authDomain: 'cinemax-app-8ea71.firebaseapp.com',
    storageBucket: 'cinemax-app-8ea71.firebasestorage.app',
    measurementId: 'G-9N653H1KM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGbqY5qsKNTANGG_ymwW14KOIEedYdPco',
    appId: '1:9580367963:android:a19ff1ad8392cdd830af7e',
    messagingSenderId: '9580367963',
    projectId: 'cinemax-app-8ea71',
    storageBucket: 'cinemax-app-8ea71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0IeM5sJjD0auvjmweCRytMZ9_Fh0aNo',
    appId: '1:9580367963:ios:10c61c5b51eef60230af7e',
    messagingSenderId: '9580367963',
    projectId: 'cinemax-app-8ea71',
    storageBucket: 'cinemax-app-8ea71.firebasestorage.app',
    iosBundleId: 'com.example.cinemaxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0IeM5sJjD0auvjmweCRytMZ9_Fh0aNo',
    appId: '1:9580367963:ios:10c61c5b51eef60230af7e',
    messagingSenderId: '9580367963',
    projectId: 'cinemax-app-8ea71',
    storageBucket: 'cinemax-app-8ea71.firebasestorage.app',
    iosBundleId: 'com.example.cinemaxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ-QomAnNC8Q5N0KNIO4mRsdX2L1fD5Do',
    appId: '1:9580367963:web:a71c2166cd35599130af7e',
    messagingSenderId: '9580367963',
    projectId: 'cinemax-app-8ea71',
    authDomain: 'cinemax-app-8ea71.firebaseapp.com',
    storageBucket: 'cinemax-app-8ea71.firebasestorage.app',
    measurementId: 'G-423KL5CJQF',
  );
}
